import 'package:flutter/material.dart';

enum Language { en, am }

final ValueNotifier<Language> languageNotifier = ValueNotifier(Language.am);

class AppStrings {
  static String get(String key) {
    final lang = languageNotifier.value;
    return _strings[lang]?[key] ?? key;
  }

  static const Map<Language, Map<String, String>> _strings = {
    Language.en: {
      'app_title': 'VIRTUAL BEGENA',
      'home': 'Home',
      'about': 'About',
      'lessons': 'Lessons',
      'contact': 'Contact',
      'enter': 'Enter',
      'get_started': 'Get Started',
      'hero_title': 'VIRTUAL BEGENA',
      'hero_subtitle': 'Master the Harp of David.\nExperience the spiritual depth of Ethiopian heritage through immersive digital lessons.',
      'start_learning': 'START LEARNING',
      'hero_how_it_works': 'See how it works',
      'feature_title': 'Why Choose Virtual Begena?',
      'feature_1_title': 'Structured Lessons',
      'feature_1_desc': 'Step-by-step guidance from beginners to advanced techniques.',
      'feature_2_title': 'Interactive Practice',
      'feature_2_desc': 'Real-time feedback and virtual strings to master the melody.',
      'feature_3_title': 'Cultural Heritage',
      'feature_3_desc': 'Learn the history and spiritual significance of the Begena.',
      'footer_subtitle': 'Bringing the ancient sounds\nto the modern world.',
      'footer_copyright': '© 2026 Virtual Begena. All rights reserved.',
      // Auth
      'sign_in': 'Sign In',
      'username': 'Username',
      'password': 'Password',
      'sign_in_cta': 'Sign In',
      'sign_out': 'Sign out',
      'welcome': 'Welcome,',
      // Dashboard
      'dashboard_title': 'Virtual Begena Trainer',
      'dashboard_subtitle': 'AI-powered traditional Ethiopian instrument practice',
      'choose_mode': 'Choose a mode to begin:',
      'mode_exercise': 'Exercise Mode',
      'mode_exercise_sub': 'Guided drills',
      'mode_free_play': 'Free Play Mode',
      'mode_free_play_sub': 'Explore freely',
      'mode_tuning': 'Tuning Mode',
      'mode_tuning_sub': 'Get in tune',
      'mode_mezmur_tenat': 'Mezmur Tenat',
      'mode_mezmur_tenat_sub': 'Learn Mezmurs',
      'mode_progress': 'My Progress',
      'mode_progress_sub': 'Track growth',
      'mode_training_plan': 'My Training Plan',
      'mode_training_plan_sub': 'AI-guided plan',
      'mode_real_play': 'Real Play Mode',
      'mode_real_play_sub': 'Play for real',
      // Streak Banner
      'streak_welcome': 'Welcome back,',
      'streak_subtitle': 'Ready to keep your streak going?',
      // Common Practice
      'correct': 'Correct',
      'wrong': 'Wrong',
      'accuracy': 'Accuracy',
      'session': 'Session',
      'restart': 'Restart',
      'exit': 'Exit',
      'back': 'Back',
      'ready': 'Ready!',
      'coming_soon': 'Coming soon',
    },
    Language.am: {
      'app_title': 'ቪርቹዋል በገና',
      'home': 'መነሻ',
      'about': 'ስለ እኛ',
      'lessons': 'ትምህርቶች',
      'contact': 'እውቂያ',
      'enter': 'ይግቡ',
      'get_started': 'ይጀምሩ',
      'hero_title': 'ቪርቹዋል በገና',
      'hero_subtitle': 'የዳዊትን በገና ይልመዱ።\nየኢትዮጵያን መንፈሳዊ ቅርስ በጥልቀት በሚያስተምሩ ዲጂታል ትምህርቶች ይለማመዱ።',
      'start_learning': 'መማር ይጀምሩ',
      'hero_how_it_works': 'እንዴት እንደሚሰራ ይመልከቱ',
      'feature_title': 'ለምን ቪርቹዋል በገናን ይመርጣሉ?',
      'feature_1_title': 'የተዋቀሩ ትምህርቶች',
      'feature_1_desc': 'ከጀማሪ እስከ ከፍተኛ ደረጃ ያሉ ደረጃ በደረጃ መመሪያዎች።',
      'feature_2_title': 'በይነተገናኝ ልምምድ',
      'feature_2_desc': 'ዜማውን ለመለማመድ የቀጥታ ግብረመልስ እና ምናባዊ አውታሮች።',
      'feature_3_title': 'ባህላዊ ቅርስ',
      'feature_3_desc': 'የበገናን ታሪክ እና መንፈሳዊ ጠቀሜታ ይወቁ።',
      'footer_subtitle': 'ጥንታዊ ድምጾችን ወደ ዘመናዊው ዓለም ማምጣት።',
      'footer_copyright': '© 2026 ቪርቹዋል በገና። መብቱ በሕግ የተጠበቀ ነው።',
      // Auth
      'sign_in': 'ይግቡ',
      'username': 'የተጠቃሚ ስም',
      'password': 'የይለፍ ቃል',
      'sign_in_cta': 'ይግቡ',
      'sign_out': 'ውጣ',
      'welcome': 'እንኳን ደህና መጡ,',
      // Dashboard
      'dashboard_title': 'ቪርቹዋል በገና ስልጠና',
      'dashboard_subtitle': 'በሰው ሰራሽ ልህቀት የተደገፈ የበገና ልምምድ',
      'choose_mode': 'ለመጀመር ሁነታ ይምረጡ:',
      'mode_exercise': 'የልምምድ ሁነታ',
      'mode_exercise_sub': 'የተመሩ ልምምዶች',
      'mode_free_play': 'ነጻ ጨዋታ ሁነታ',
      'mode_free_play_sub': 'በነጻነት ይለማመዱ',
      'mode_tuning': 'ማስተካከያ ሁነታ',
      'mode_tuning_sub': 'በገናዎን ያስተካክሉ',
      'mode_mezmur_tenat': 'መዝሙር ጥናት',
      'mode_mezmur_tenat_sub': 'መዝሙሮችን ይማሩ',
      'mode_progress': 'የእኔ እድገት',
      'mode_progress_sub': 'እድገትዎን ይከታተሉ',
      'mode_training_plan': 'የስልጠና እቅዴ',
      'mode_training_plan_sub': 'ሰው ሰራሽ ልህቀት የመራው እቅድ',
      'mode_real_play': 'እውነተኛ ጨዋታ ሁነታ',
      'mode_real_play_sub': 'በእውነተኛ በገና ይጫወቱ',
      // Streak Banner
      'streak_welcome': 'እንኳን ደህና መጡ,',
      'streak_subtitle': 'ለቀጣይ ልምምድ ዝግጁ ነዎት?',
      // Common Practice
      'correct': 'ትክክል',
      'wrong': 'ስህተት',
      'accuracy': 'ትክክለኛነት',
      'session': 'ክፍለ ጊዜ',
      'restart': 'እንደገና ጀምር',
      'exit': 'ውጣ',
      'back': 'ተመለስ',
      'ready': 'ተዘጋጅቷል!',
      'coming_soon': 'በቅርቡ ይጠብቁ',
    },
  };
}
