import 'package:flutter/material.dart';

enum Language { en, am }

final ValueNotifier<Language> languageNotifier = ValueNotifier(Language.am);

class AppStrings {
  static String get(String key) {
    final lang = languageNotifier.value;
    return _strings[lang]?[key] ?? key;
  }

  static const Map<Language, Map<String, String>> _strings = {
    Language.en: {
      'app_title': 'VIRTUAL BEGENA',
      'home': 'Home',
      'about': 'About',
      'shop': 'Shop',
      'lessons': 'Lessons',
      'contact': 'Contact',
      'enter': 'Enter',
      'get_started': 'Get Started',
      'hero_title': 'VIRTUAL BEGENA',
      'hero_subtitle': 'Master the Harp of David.\nExperience the spiritual depth of Ethiopian heritage through immersive digital lessons.',
      'start_learning': 'START LEARNING',
      'hero_how_it_works': 'See how it works',
      'feature_title': 'Why Choose Virtual Begena?',
      'feature_1_title': 'Structured Lessons',
      'feature_1_desc': 'Step-by-step guidance from beginners to advanced techniques.',
      'feature_2_title': 'Interactive Practice',
      'feature_2_desc': 'Real-time feedback and virtual strings to master the melody.',
      'feature_3_title': 'Cultural Heritage',
      'feature_3_desc': 'Learn the history and spiritual significance of the Begena.',
      'footer_subtitle': 'Bringing the ancient sounds\nto the modern world.',
      'footer_copyright': '© 2026 Virtual Begena. All rights reserved.',
      // Auth
      'sign_in': 'Sign In',
      'username': 'Username',
      'password': 'Password',
      'sign_in_cta': 'Sign In',
      'sign_out': 'Sign out',
      'welcome': 'Welcome,',
      // Dashboard
      'dashboard_title': 'Virtual Begena Trainer',
      'dashboard_subtitle': 'AI-powered traditional Ethiopian instrument practice',
      'choose_mode': 'Choose a mode to begin:',
      'mode_exercise': 'Exercise Mode',
      'mode_exercise_sub': 'Guided drills',
      'mode_free_play': 'Free Play Mode',
      'mode_free_play_sub': 'Explore freely',
      'mode_tuning': 'Tuning Mode',
      'mode_tuning_sub': 'Get in tune',
      'mode_mezmur_tenat': 'Mezmur Tenat',
      'mode_mezmur_tenat_sub': 'Learn Mezmurs',
      'mode_progress': 'My Progress',
      'mode_progress_sub': 'Track growth',
      'mode_training_plan': 'My Training Plan',
      'mode_training_plan_sub': 'AI-guided plan',
      'mode_real_play': 'Real Play Mode',
      'mode_real_play_sub': 'Play for real',
      // Streak Banner
      'streak_welcome': 'Welcome back,',
      'streak_subtitle': 'Ready to keep your streak going?',
      // Common Practice
      'correct': 'Correct',
      'wrong': 'Wrong',
      'accuracy': 'Accuracy',
      'session': 'Session',
      'restart': 'Restart',
      'exit': 'Exit',
      'back': 'Back',
      'ready': 'Ready!',
      'coming_soon': 'Coming soon',
      // About page
      'about_lead': "Virtual Begena brings one of Ethiopia's oldest instruments into your browser. No begena at home, no problem — your camera becomes the strings.",
      'about_what_heading': 'What is the Begena?',
      'about_what_body': 'The begena is a large, ten-stringed lyre with deep roots in Ethiopian Orthodox Tewahedo tradition. Often called the "harp of King David," it isn\'t played for entertainment in the usual sense — its low, resonant tones are meant to quiet the mind, accompanying prayer, reflection, and the fasting seasons of the church calendar. Learning begena has traditionally meant learning from a teacher, string by string, often over years.',
      'about_why_heading': 'Why Virtual Begena',
      'about_why_body': "Not everyone has access to a begena or a teacher nearby. Virtual Begena uses your webcam and real-time hand tracking to let you practice finger positions and plucking technique against a virtual set of strings — no instrument required to start building the muscle memory. It's a stepping stone toward the real instrument, not a replacement for the tradition it comes from.",
      'about_how_heading': 'How it works',
      'about_how_body': "Your camera watches your hand. When you pluck a virtual string in the right position, you'll hear the correct tone and see the string respond. Get it wrong, and you'll see and hear that too — the app is built to give you honest, immediate feedback so you can correct as you go, the way a teacher would.",
      'about_note_heading': 'A note on tradition',
      'about_note_body': 'This app is a practice tool, built with respect for an instrument that carries deep spiritual and cultural meaning. We encourage learners to seek out real begena teachers and communities as they progress.',
      // Lessons page
      'lessons_intro': 'Begena music is organized around qenet — traditional modes, each with its own mood and character. Virtual Begena currently supports three:',
      'qenet_selamta_title': 'Selamta',
      'qenet_selamta_desc': 'A warm, grounding mode often used as a starting point for new players. Good for building basic finger-to-string coordination before moving to more expressive modes.',
      'qenet_tezeta_title': 'Tezeta',
      'qenet_tezeta_desc': 'Reflective and melancholic — tezeta means "memory" or "nostalgia." This mode is where subtlety in timing and pressure starts to matter more than raw accuracy.',
      'qenet_anchihoye_title': 'Anchihoye',
      'qenet_anchihoye_desc': 'Livelier and more rhythmic. A good test of whether your finger-to-string mapping has become automatic rather than something you have to think through.',
      'practice_structure_heading': 'How practice is structured',
      'mode_exercise_full_title': 'Exercise Mode',
      'mode_exercise_full_desc': "Guided, one string at a time. The app tells you which finger to pluck next, tracks your accuracy, and adapts based on which fingers you're consistently getting right or wrong — so you spend more time on what actually needs work.",
      'mode_free_play_full_title': 'Free Play',
      'mode_free_play_full_desc': 'No prompts, no scoring. Just you, the strings, and whichever qenet you choose. Good for warming up or for playing something you already know.',
      'mode_real_play_full_title': 'Real Play',
      'mode_real_play_full_desc': "Full performance mode — plays like a real session, letting you apply what you've built in Exercise Mode without the training wheels.",
      'tips_heading': 'Tips for getting started',
      'tip_calibrate': 'Calibrate your string positions before your first session (Settings → Calibrate) — it only takes a few seconds and makes detection far more accurate for your hand and camera angle.',
      'tip_show_strings': 'Turn on "Show Strings" while you\'re still learning where each string sits — turn it off once you don\'t need the visual crutch anymore, closer to how you\'d eventually play without looking.',
      'tip_start_selamta': 'Start in Selamta before moving to Tezeta or Anchihoye — the modes are ordered roughly by difficulty of feel, not just tradition.',
    },
    Language.am: {
      'app_title': 'ቪርቹዋል በገና',
      'home': 'መነሻ',
      'about': 'ስለ እኛ',
      'shop': 'ግዢ',
      'lessons': 'ትምህርቶች',
      'contact': 'እውቂያ',
      'enter': 'ይግቡ',
      'get_started': 'ይጀምሩ',
      'hero_title': 'ቪርቹዋል በገና',
      'hero_subtitle': 'የዳዊትን በገና ይልመዱ።\nየኢትዮጵያን መንፈሳዊ ቅርስ በጥልቀት በሚያስተምሩ ዲጂታል ትምህርቶች ይለማመዱ።',
      'start_learning': 'መማር ይጀምሩ',
      'hero_how_it_works': 'እንዴት እንደሚሰራ ይመልከቱ',
      'feature_title': 'ለምን ቪርቹዋል በገናን ይመርጣሉ?',
      'feature_1_title': 'የተዋቀሩ ትምህርቶች',
      'feature_1_desc': 'ከጀማሪ እስከ ከፍተኛ ደረጃ ያሉ ደረጃ በደረጃ መመሪያዎች።',
      'feature_2_title': 'በይነተገናኝ ልምምድ',
      'feature_2_desc': 'ዜማውን ለመለማመድ የቀጥታ ግብረመልስ እና ምናባዊ አውታሮች።',
      'feature_3_title': 'ባህላዊ ቅርስ',
      'feature_3_desc': 'የበገናን ታሪክ እና መንፈሳዊ ጠቀሜታ ይወቁ።',
      'footer_subtitle': 'ጥንታዊ ድምጾችን ወደ ዘመናዊው ዓለም ማምጣት።',
      'footer_copyright': '© 2026 ቪርቹዋል በገና። መብቱ በሕግ የተጠበቀ ነው።',
      // Auth
      'sign_in': 'ይግቡ',
      'username': 'የተጠቃሚ ስም',
      'password': 'የይለፍ ቃል',
      'sign_in_cta': 'ይግቡ',
      'sign_out': 'ውጣ',
      'welcome': 'እንኳን ደህና መጡ,',
      // Dashboard
      'dashboard_title': 'ቪርቹዋል በገና ስልጠና',
      'dashboard_subtitle': 'በሰው ሰራሽ ልህቀት የተደገፈ የበገና ልምምድ',
      'choose_mode': 'ለመጀመር ሁነታ ይምረጡ:',
      'mode_exercise': 'የልምምድ ሁነታ',
      'mode_exercise_sub': 'የተመሩ ልምምዶች',
      'mode_free_play': 'ነጻ ጨዋታ ሁነታ',
      'mode_free_play_sub': 'በነጻነት ይለማመዱ',
      'mode_tuning': 'ማስተካከያ ሁነታ',
      'mode_tuning_sub': 'በገናዎን ያስተካክሉ',
      'mode_mezmur_tenat': 'መዝሙር ጥናት',
      'mode_mezmur_tenat_sub': 'መዝሙሮችን ይማሩ',
      'mode_progress': 'የእኔ እድገት',
      'mode_progress_sub': 'እድገትዎን ይከታተሉ',
      'mode_training_plan': 'የስልጠና እቅዴ',
      'mode_training_plan_sub': 'ሰው ሰራሽ ልህቀት የመራው እቅድ',
      'mode_real_play': 'እውነተኛ ጨዋታ ሁነታ',
      'mode_real_play_sub': 'በእውነተኛ በገና ይጫወቱ',
      // Streak Banner
      'streak_welcome': 'እንኳን ደህና መጡ,',
      'streak_subtitle': 'ለቀጣይ ልምምድ ዝግጁ ነዎት?',
      // Common Practice
      'correct': 'ትክክል',
      'wrong': 'ስህተት',
      'accuracy': 'ትክክለኛነት',
      'session': 'ክፍለ ጊዜ',
      'restart': 'እንደገና ጀምር',
      'exit': 'ውጣ',
      'back': 'ተመለስ',
      'ready': 'ተዘጋጅቷል!',
      'coming_soon': 'በቅርቡ ይጠብቁ',
      // About page
      'about_lead': 'ቪርቹዋል በገና ከኢትዮጵያ ጥንታዊ መሳሪያዎች አንዱን ወደ አሳሽዎ ያመጣል። በቤትዎ በገና ከሌለዎት ምንም ችግር የለውም — ካሜራዎ አውታሮቹ ይሆናል።',
      'about_what_heading': 'በገና ምንድን ነው?',
      'about_what_body': 'በገና በኢትዮጵያ ኦርቶዶክስ ተዋሕዶ ትውፊት ውስጥ ጥልቅ ሥር ያለው ትልቅ የአስር አውታር በገና ነው። ብዙ ጊዜ "የዳዊት በገና" ተብሎ የሚጠራው፣ በተለምዶ ለመዝናኛ የሚጫወት አይደለም — ዝቅተኛና ጥልቅ ድምጹ አእምሮን ለማረጋጋት፣ ጸሎትን፣ ማሰላሰልን እና የአጽዋማት ወቅቶችን ለማጀብ የታሰበ ነው። በገናን መማር በተለምዶ ማለት ከመምህር ጋር በአውታር በአውታር፣ ብዙ ጊዜም በዓመታት ውስጥ መማር ማለት ነው።',
      'about_why_heading': 'ለምን ቪርቹዋል በገና',
      'about_why_body': 'ሁሉም ሰው በገና ወይም በአቅራቢያ መምህር የለውም። ቪርቹዋል በገና ካሜራዎን እና የቅጽበት እጅ ክትትልን በመጠቀም የጣት አቀማመጥን እና የመጎተት ክህሎትን በምናባዊ አውታሮች ላይ እንዲለማመዱ ያስችልዎታል — ጡንቻ ትውስታን ለመገንባት ምንም መሳሪያ አያስፈልግም። ወደ እውነተኛው መሳሪያ የሚያደርስ እርምጃ ነው እንጂ የመጣበትን ትውፊት የሚተካ አይደለም።',
      'about_how_heading': 'እንዴት እንደሚሰራ',
      'about_how_body': 'ካሜራዎ እጅዎን ይከታተላል። ምናባዊ አውታርን በትክክለኛው ቦታ ሲጎትቱ ትክክለኛውን ድምጽ ይሰማሉ እንዲሁም አውታሩ ምላሽ ሲሰጥ ያያሉ። ስህተት ከሠሩ ያንንም ያያሉ እና ይሰማሉ — መተግበሪያው እንደ መምህር በሚያደርገው መንገድ በሂደት እንዲያርሙ ሐቀኛና ፈጣን ግብረመልስ እንዲሰጥዎት ተደርጎ የተሠራ ነው።',
      'about_note_heading': 'ስለ ትውፊት አጭር ማስታወሻ',
      'about_note_body': 'ይህ መተግበሪያ ጥልቅ መንፈሳዊና ባህላዊ ትርጉም ላለው መሳሪያ በአክብሮት የተሠራ የልምምድ መሣሪያ ነው። ተማሪዎች እየገፉ ሲሄዱ እውነተኛ የበገና መምህራንን እና ማህበረሰቦችን እንዲፈልጉ እናበረታታለን።',
      // Lessons page
      'lessons_intro': 'የበገና ሙዚቃ በቅኔት — በባህላዊ ስልቶች፣ እያንዳንዳቸው የራሳቸው ስሜትና ባህሪ ባላቸው ላይ የተመሠረተ ነው። ቪርቹዋል በገና በአሁኑ ጊዜ ሦስት ይደግፋል፦',
      'qenet_selamta_title': 'ሰላምታ',
      'qenet_selamta_desc': 'ለአዲስ ተጫዋቾች እንደ መነሻ ነጥብ የሚያገለግል ሞቅ ያለና መሠረት የሚጥል ስልት። ወደ ይበልጥ ገላጭ ስልቶች ከመሄድዎ በፊት መሠረታዊ የጣት-ወደ-አውታር ቅንጅትን ለመገንባት ጥሩ ነው።',
      'qenet_tezeta_title': 'ጤዜታ',
      'qenet_tezeta_desc': 'ማሰላሰያና ናፍቆት የተሞላበት — ጤዜታ ማለት "ትውስታ" ወይም "ናፍቆት" ማለት ነው። በዚህ ስልት ውስጥ የጊዜ አጠቃቀምና የግፊት ስሱነት ከትክክለኛነት በላይ ወሳኝ መሆን ይጀምራል።',
      'qenet_anchihoye_title': 'አንቺሆዬ',
      'qenet_anchihoye_desc': 'ይበልጥ ሕያውና ምት ያለው። የጣት-ወደ-አውታር ትስስርዎ ማሰብ የማያስፈልገው ራሱ በራሱ ደረጃ ላይ መድረሱን ለመፈተሽ ጥሩ ነው።',
      'practice_structure_heading': 'ልምምድ እንዴት እንደተዋቀረ',
      'mode_exercise_full_title': 'የልምምድ ሁነታ',
      'mode_exercise_full_desc': 'በአንድ ጊዜ አንድ አውታር በተመራ መልኩ። መተግበሪያው ቀጥሎ የትኛውን ጣት መጎተት እንዳለብዎ ይነግርዎታል፣ ትክክለኛነትዎን ይከታተላል፣ እንዲሁም በየትኞቹ ጣቶች ላይ በተከታታይ ትክክል ወይም ስህተት እንደሚሠሩ መሠረት ያደርጋል — ስለዚህ ትክክለኛ ትኩረት በሚያስፈልገው ላይ ብዙ ጊዜ ያሳልፋሉ።',
      'mode_free_play_full_title': 'ነጻ ጨዋታ',
      'mode_free_play_full_desc': 'ምንም መመሪያ የለም፣ ውጤትም አይሰላም። እርስዎ፣ አውታሮቹ፣ እና የመረጡት ቅኔት ብቻ። ለማሞቂያ ወይም አስቀድመው ለሚያውቁት ነገር መጫወት ጥሩ ነው።',
      'mode_real_play_full_title': 'እውነተኛ ጨዋታ',
      'mode_real_play_full_desc': 'የተሟላ የአፈጻጸም ሁነታ — እንደ እውነተኛ ክፍለ ጊዜ ይጫወታል፣ በልምምድ ሁነታ የገነቡትን ያለ ድጋፍ እንዲተገብሩ ያስችልዎታል።',
      'tips_heading': 'ለመጀመር የሚረዱ ምክሮች',
      'tip_calibrate': 'ከመጀመሪያ ክፍለ ጊዜዎ በፊት የአውታር ቦታዎችን ያስተካክሉ (ቅንብሮች → ማስተካከያ) — ጥቂት ሰከንዶች ብቻ ይወስዳል እንዲሁም ለእጅዎና ለካሜራ አንግልዎ ማወቂያውን በጣም ትክክለኛ ያደርገዋል።',
      'tip_show_strings': 'እያንዳንዱ አውታር የት እንዳለ እየተማሩ ሳሉ "አውታሮችን አሳይ"ን ያብሩ — የዕይታ እርዳታ ከማያስፈልግዎ በኋላ ያጥፉት፣ ይህም ወደፊት ሳያዩ ወደሚጫወቱበት ሁኔታ ይበልጥ ያቀርብዎታል።',
      'tip_start_selamta': 'ወደ ጤዜታ ወይም አንቺሆዬ ከመሄድዎ በፊት በሰላምታ ይጀምሩ — ስልቶቹ በተለምዶ ብቻ ሳይሆን በስሜት ውስብስብነት ደረጃ በግምት የተደረደሩ ናቸው።',
    },
  };
}
